### PR TITLE
frontend setup

### PR DESCRIPTION
**Pull request by bray79**
# Description
Please include a summary of the change and which issue is fixed. Include the motivation and context, and list any dependencies that are required for this change.

- Created frontend directory and folders

# Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- Ran ng serve while in the frontend directory and after npm install
- Went to the localhost and ensured it loads with no errors (should be a blank screen)

# Checklist:
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by micahvanm** [comment]
Looks pretty alright to me, made to be all in the one folder? For my demo to be useful I changed some lines in package.json to use concurrently and such small differences

**Comment by bray79** [comment]
> Looks pretty alright to me, made to be all in the one folder? For my demo to be useful I changed some lines in package.json to use concurrently and such small differences

Yeah I believe there should be a folder for frontend and a folder for backend. And awesome could you approve this so we can merge what all we have together?

**Review by AndreasInk — APPROVED** [review]
Looks good to me!

**Comment by micahvanm** [comment]
Yeah it looks fine to me as far as I can tell. worst case we can copy-paste code from our local copies and move stuff around to accommodate.

**Pull request merged**
